routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('food.home'));
});

Route::get('/admin',  function () {
    return redirect(route('admin.dashboard'));
})->name('admin')->middleware('auth', 'verified');

//favor especial para vale
Route::get('/vale_semaforo/{quien}/{respuesta}', '\App\Http\Controllers\Auth\LoginController@vale_semaforo');


Auth::routes(['verify' => true]);
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('/images/public/{path}/{filename}', 'ImagesController@public_image')->name('images.public');
Route::get('/facturas/{id}/pagar', 'FacturacionController@pagarFactura')->name('facturas.pago')->middleware('auth', 'verified');
Route::get('/facturas/{id}/procesar_pago_879827365', 'FacturacionController@procesarPago')->name('facturas.procesar_pago');
Route::middleware('auth', 'verified')->get('/archivos_negocio/{path}/{filename}', 'FilesController@negocio_private_file')->name('files.negocio');

/**
 * ADMIN
 */
Route::middleware('cache.headers:no_cache,private,max_age='.env('CACHE_TIME_BACK', '60').';etag')->middleware('auth', 'verified')->prefix('admin')->name('admin.')->group(function () {
    Route::get('/dashboard', 'Admin\AdminController@index')
        ->name('dashboard');
    Route::resource('horarios', 'Admin\HorariosController');
    Route::resource('negocios', 'Admin\NegociosController');
    Route::get('negocios/{id}/configurar_envios', 'Admin\NegociosController@envios')
        ->name('negocios.envios.edit');
    Route::put('negocios/{id}/configurar_envios', 'Admin\NegociosController@envios_update')
        ->name('negocios.envios.update');
    Route::put('negocios/{id}/slug_update', 'Admin\NegociosController@slug_update')
        ->name('negocios.slug.update');
    Route::put('negocios/{id}/configurar_tiempo', 'Admin\NegociosController@tiempo_update')
        ->name('negocios.tiempo.update');
    Route::get('negocios/{id}/borrar_tiempo', 'Admin\NegociosController@tiempo_delete')
        ->name('negocios.tiempo.delete');
    Route::get('negocios/{id}/configurar_pago', 'Admin\NegociosController@pago_edit')
        ->name('negocios.pago.edit');
    Route::put('negocios/{id}/configurar_pago', 'Admin\NegociosController@pago_update')
        ->name('negocios.pago.update');
    Route::get('negocios/{id}/configurar_categorias', 'Admin\NegociosController@categorias_edit')
        ->name('restaurantes.categorias.edit');
    Route::put('negocios/{id}/configurar_categorias', 'Admin\NegociosController@categorias_update')
        ->name('restaurantes.categorias.update');
    Route::get('negocios/{id}/configurar_notificaciones', 'Admin\NegociosController@notificaciones_edit')
        ->name('negocios.notificaciones.edit');
    Route::put('negocios/{id}/configurar_notificaciones', 'Admin\NegociosController@notificaciones_update')
        ->name('negocios.notificaciones.update');

    //sucursales
    Route::get('negocios/{id}/sucursales', 'Admin\SucursalesController@index')
        ->name('negocios.sucursales.index');
    Route::get('negocios/{id}/sucursales/create', 'Admin\SucursalesController@create')
        ->name('negocios.sucursales.create');
    Route::post('negocios/{id}/sucursales/create', 'Admin\SucursalesController@store')
        ->name('negocios.sucursales.store');
    Route::post('negocios/{id}/sucursales/{sucursal_id}/select', 'Admin\SucursalesController@select')
        ->name('negocios.sucursales.select');
    Route::post('negocios/{id}/sucursales/select', 'Admin\SucursalesController@select_sucursal')
        ->name('negocios.sucursales.selectsucursal');

    Route::get('pedidos', 'Admin\PedidosController@index')
        ->name('pedidos.index');
    Route::get('pedidos/{id}/actualizar_status/{status}', 'Admin\PedidosController@actualizar_status')
        ->name('pedidos.update_status');
    Route::post('pedidos/{id}/actualizar_status/{status}', 'Admin\PedidosController@actualizar_status')
        ->name('pedidos.update_status');
    Route::get('pedidos/historial', 'Admin\PedidosController@historial')->name('pedidos.historial');
    Route::get('pedidos/historial_detallado', 'Admin\PedidosController@historial_detallado')->name('pedidos.historial_detallado');

    //perfil
    Route::get('perfil', 'Admin\PerfilController@edit')->name('perfil.edit');
    Route::put('perfil', 'Admin\PerfilController@update')->name('perfil.update');

    /*
     * Restaurantes
     * */

    Route::resource('categorias-de-platillos', 'Admin\Restaurantes\PlatillocategoriasController')->names([
        'index' => 'platillocategorias.index',
        'create' => 'platillocategorias.create',
        'store' => 'platillocategorias.store',
        'show' => 'platillocategorias.show',
        'edit' => 'platillocategorias.edit',
        'update' => 'platillocategorias.update',
        'destroy' => 'platillocategorias.destroy',
    ]);
    Route::get('categorias-de-platillos/{id}/order/{action}', 'Admin\Restaurantes\PlatillocategoriasController@order')
        ->name('platillocategorias.order');
    Route::resource('platillos', 'Admin\Restaurantes\PlatillosController');
    Route::get('platillos/{id}/order/{action}', 'Admin\Restaurantes\PlatillosController@order')
        ->name('platillos.order');
    Route::resource('operadores', 'Admin\OperadoresController');
    Route::resource('facturas', 'Admin\FacturasController');
    Route::get('facturas/{id}/desglose', 'Admin\FacturasController@bajar_desglose')
        ->name('facturas.desglose');
    Route::resource('tutoriales', 'Admin\TutorialesController');

    /*
     * Facturas
     */
    Route::get('/facturas/{id}/solicitar_factura', 'FacturacionController@solicitarFactura')->name('facturas.solicitar_factura');
});

/**
 * SUPERADMIN
 */

Route::middleware('cache.headers:no_cache,private,max_age='.env('CACHE_TIME_BACK', '60').';etag')->middleware('auth', 'verified')->prefix('superadmin')->name('superadmin.')->group(function () {
    Route::get('/superadmin/negocios', 'Admin\NegociosController@index')->name('negocios.index');
    Route::get('/superadmin/negocios/solicitudes', 'Admin\NegociosController@solicitudes')->name('negocios.solicitudes');
    Route::get('/superadmin/negocios/{id}/verificar', 'Admin\NegociosController@verificar')->name('negocios.verificar');
    Route::resource('regiones', 'Admin\RegionesController');
    Route::get('/pedidos/historial_superadmin', 'Admin\PedidosController@historial_admin')->name('pedidos.historial_superadmin');
});



/**
 *  UKI Food
 */
Route::middleware('cache.headers:no_cache,private,max_age='.env('CACHE_TIME_FRONT', '60').';etag')->prefix('food')->name('food.')->group(function () {
    Route::get('/', '\App\Http\Controllers\Food\DirectoryController@index')->name('home');
    Route::middleware(\App\Http\Middleware\NeedsLocation::class)->get('/categorias/{id}', '\App\Http\Controllers\Food\DirectoryController@categoriaListado')->name('categoria.show');
    Route::middleware(\App\Http\Middleware\NeedsLocation::class)->get('/restaurantes/buscar', '\App\Http\Controllers\Food\DirectoryController@buscar')->name('restaurante.search');
    Route::get('/restaurantes/{id}', '\App\Http\Controllers\Food\DirectoryController@restauranteListado')->name('restaurante.show');
    Route::get('/restaurantes/menu/{id}', '\App\Http\Controllers\Food\DirectoryController@menuOnline')->name('restaurante.menu.show');
    Route::middleware(\App\Http\Middleware\NeedsLocation::class)->get('/platillos/{id}', '\App\Http\Controllers\Food\DirectoryController@platilloDetalle')->name('platillo.show');
    Route::get('/platillos/{id}/{itemId}', '\App\Http\Controllers\Food\DirectoryController@platilloEdit')->name('platillo.edit');
    Route::get('/perfil/region/{region_id}', '\App\Http\Controllers\Food\PerfilController@configurarRegion')->name('perfil.region.update');
    Route::get('/perfil/ubicacion/{lat}/{lon}', '\App\Http\Controllers\Food\PerfilController@configurarUbicacion')->name('perfil.ubicacion.update');
    Route::get('/buscar-direccion/{lat}/{lon}', '\App\Http\Controllers\Food\PerfilController@searchAdress')->name('perfil.ubicacion.buscar');
    Route::get('/perfil', '\App\Http\Controllers\Food\PerfilController@edit')->name('perfil.edit');
    Route::put('/perfil', '\App\Http\Controllers\Food\PerfilController@update')->name('perfil.update');
    Route::get('perfil/comparte_ubicacion', '\App\Http\Controllers\Food\PerfilController@editLocation')->name('perfil.location.edit');

    /**
     * Cart
     */
    Route::post('/carrito/restaurante/{id}/items', '\App\Http\Controllers\Food\CarritoController@add')->name('cart.items.add');
    Route::put('/carrito/restaurante/{id}/items/{item_id}', '\App\Http\Controllers\Food\CarritoController@update')->name('cart.items.update');
    Route::get('/carrito/restaurante/{negocio_id}/items/{item_id}/eliminar', '\App\Http\Controllers\Food\CarritoController@delete')->name('cart.items.delete');
    Route::post('/carrito', '\App\Http\Controllers\Food\CarritoController@procesar')->name('cart.process');
    Route::post('/confirmar', '\App\Http\Controllers\Food\CarritoController@confirmar')->name('cart.confirm');
    Route::get('/carrito', '\App\Http\Controllers\Food\CarritoController@index')->name('cart.show');
    Route::get('/carrito/vaciar', '\App\Http\Controllers\Food\CarritoController@clear')->name('cart.clear');

    Route::get('/pedido/{id}', '\App\Http\Controllers\Food\CarritoController@seguimiento_pedido')->name('pedido.seguimiento');
    //Route::get('pedidos/{id}/entregado', 'Admin\PedidosController@actualizar_status_front')

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <p style="margin: 0px;">Hola, {{\Illuminate\Support\Facades\Auth::user()->name}}</p>
            <h1 class="db-header-title">{{$negocio->nombre}}</h1>
            @if($negocio->adeudo)
            <div class="alert alert-danger">
                <h3 style="color: #900;"><i class="fa fa-info-circle"></i> IMPORTANTE: SITIO DESACTIVADO</h3>
                <p><big>Actualmente cuentas con adeudo en uno o más de tus recibos, Accede a la sección <a href="{{route('admin.facturas.index')}}">Estado de Cuenta</a> para poder reactivar tu restaurante.</big></p>
            </div>
            @endif
        </div>

        <div class="col-md-12">
            <div class="ms-panel">
                <div class="ms-panel-header">
                    <h6>
                        Estadísticas generales de
                        {{\App\Helpers\DateHelper::mes_letra(date('m'))}}
                        {{ \Carbon\Carbon::now()->formatLocalized('%Y') }}
                    </h6>
                    <p class="alert alert-info"><i class="fa fa-info-circle"></i> La información del mes pasado y los porcentajes se calculan utilizando el acumulado del mes corriente en comparación al total del mes pasado.</p>
                </div>
                <div class="ms-panel-body">

        <div class="row row-eq-height">
                <!-- Ventas -->
            @component('admin.components.tarjeta_dashboard')
                @slot('tipo', 'dinero')
                @slot('titulo', 'Ventas')
                @slot('resumen', $negocio->resumen_ventas())
            @endcomponent

            <!-- Pedidos -->
            @component('admin.components.tarjeta_dashboard')
                @slot('tipo', 'pedidos')
                @slot('titulo', 'Pedidos')
                @slot('resumen', $negocio->resumen_pedidos())
            @endcomponent

            <!-- Ticket Promedio -->
            @component('admin.components.tarjeta_dashboard')
                @slot('tipo', 'dinero')
                @slot('titulo', 'Ticket Promedio')
                @slot('resumen', $negocio->resumen_ticket_promedio())
            @endcomponent

            <!-- Comisiones UKI -->
            @component('admin.components.tarjeta_dashboard')
                @slot('tipo', 'dinero')
                @slot('iva', 'incluido')
                @slot('titulo', 'Comisiones Uki')
                @slot('disclaimer', '*')
                @slot('resumen', $negocio->resumen_comisiones_uki())
            @endcomponent

            <!-- Ganancia -->
            @component('admin.components.tarjeta_dashboard')
                @slot('tipo', 'dinero')
                @slot('titulo', 'Ganancia')
                @slot('resumen', $negocio->resumen_ganancia())
            @endcomponent

            <!-- porcentaje de Ganancia -->
            @component('admin.components.tarjeta_dashboard')
                @slot('tipo', 'porcentaje')
                @slot('titulo', '% de Ganancia')
                @slot('resumen', $negocio->resumen_porcentaje_ganancia())
            @endcomponent

            <!-- Pedidos pickup-->
            @component('admin.components.tarjeta_dashboard')
                @slot('tipo', 'pedidos')
                @slot('titulo', 'Pedidos Pick up & GO')
                @slot('resumen', $negocio->resumen_pedidos_pickup())
            @endcomponent

            <!-- Ingresos envios -->
            @component('admin.components.tarjeta_dashboard')
                @slot('tipo', 'dinero')
                @slot('titulo', 'Ingresos por envios')
                @slot('resumen', $negocio->resumen_ingresos_envios())
            @endcomponent


                </div>
                    <p><small>* Las comisiones UKI&reg; toman en cuenta los pedidos cancelados.</small></p>
                </div>
            </div>

        </div>


        <!-- Food Orders -->
        <div class="col-md-12">
            <div class="ms-panel">
                <div class="ms-panel-header">
                    <h6>Lo más pedido en este mes</h6>
                </div>
                <div class="ms-panel-body">
                    <div class="row">
                        @foreach($negocio->mas_pedidos() as $platillo)
                            <div class="col-xl-3 col-lg-6 col-md-6 col-sm-6" style="margin-bottom: 20px;">
                                <div class="ms-card no-margin" style="height: 100%;">
                                    <div class="ms-card-img">
                                        <?php $platillo_obj = \App\Models\Restaurantes\Platillo::where('nombre',
                                            $platillo->platillo)->first() ?>
                                        @if($platillo_obj->foto)
                                            <img class="img-fluid img-platillo-dashboard"
                                                 src="{{route('images.public', [base64_encode('restaurantes/platillos/'), $platillo_obj->foto])}}"/>
                                        @else
                                            <img class="img-fluid img-platillo-dashboard"
                                                 src="{{URL::to('/assets/img')}}/sin_imagen.jpg"/>
                                        @endif
                                    </div>
                                    <div class="ms-card-body">
                                        <div class="ms-card-heading-title">
                                            <h6>{{$platillo->platillo}}</h6>
                                            <span
                                                class="green-text"><strong>$ {{number_format($platillo->costo_unitario, 2, '.', ',')}}</strong></span>
                                        </div>

                                        <div class="ms-card-heading-title">
                                            <p>Pedidos <span class="red-text">{{$platillo->count}}</span></p>
                                            <p>Ingreso <span
                                                    class="red-text">$ {{number_format($platillo->costo_unitario * $platillo->count, 2, '.', ',')}}</span>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
        <!-- END/Food Orders -->
        <div class="col-xl-6 col-lg-12">
            <div class="ms-panel">
                <div class="ms-panel-header">
                    <h6>
                        Código QR de restaurante
                    </h6>
                </div>
                <div class="ms-panel-body">
                    <br/><h5>QR de tienda en linea</h5>
                    <div class="row">
                        <div class="col-md-12">
                            <a href="https://chart.googleapis.com/chart?chs=500x500&cht=qr&chl={{urlencode(route('food.restaurante.show', $negocio->id))}}" target="_blank" download>
                                <img style="width: 100px;" src="https://chart.googleapis.com/chart?chs=200x200&cht=qr&chl={{urlencode(route('food.restaurante.show', $negocio->id))}}&choe=UTF-8">
                            </a>
                            <a  href="https://chart.googleapis.com/chart?chs=500x500&cht=qr&chl={{urlencode(route('food.restaurante.show', $negocio->id))}}" target="_blank" download>
                                Descargar código QR
                            </a>
                        </div>
                    </div>
                    <br/><h5>QR de menú digital</h5>
                    <div class="row">
                        <div class="col-md-12">
                            <a href="https://chart.googleapis.com/chart?chs=500x500&cht=qr&chl={{urlencode(route('food.restaurante.menu.show', $negocio->id))}}" target="_blank" download>
                                <img style="width: 100px;" src="https://chart.googleapis.com/chart?chs=200x200&cht=qr&chl={{urlencode(route('food.restaurante.show', $negocio->id))}}&choe=UTF-8">
                            </a>
                            <a  href="https://chart.googleapis.com/chart?chs=500x500&cht=qr&chl={{urlencode(route('food.restaurante.menu.show', $negocio->id))}}" target="_blank" download>
                                Descargar código QR
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-6 col-lg-12">
            <div class="ms-panel">
                <div class="ms-panel-header">
                    <h6>
                        Enlace de restaurante
                    </h6>
                </div>
                <div class="ms-panel-body">
                    <div class="row">
                        <div class="col-md-12">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul style="margin: 0px;">
                                        @foreach ($errors->all() as $error)
                                            <li><i class="flaticon-alert"></i> {{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <div class="form-group">
                                <form method="post" action="{{route('admin.negocios.slug.update', $negocio->id)}}">
                                    {{method_field('put')}}
                                    {{ csrf_field() }}
                                    <label for="codigo">URL Amigable de tu restaurante</label>
                                    <input type="text" class="form-control @error('slug') is-invalid @enderror"
                                           id="slug" name="slug" placeholder="tu-restaurante"
                                           value="{{old('slug')?old('slug'):$negocio->config->slug}}">
                                    <p style="text-align: right"><input type="submit" class="btn btn-primary" value="Guardar"></p>
                                </form>
                            </div>
                            <br/><h5>Enlace de tienda en linea</h5>
                            <p class="alert alert-info">
                                {{route('food.restaurante.show', $negocio->slugOrId())}}
                            </p>
                            <p style="text-align: right">
                                <a href="#" class="btnCopiarEnlace" target="_blank" download>
                                    Copiar enlace
                                </a>
                            </p>
                                <br/><h5>Enlace de menú digital</h5>
                                <p class="alert alert-info">
                                    {{route('food.restaurante.menu.show', $negocio->slugOrId())}}
                                </p>
                                <p style="text-align: right">
                                    <a href="#" class="btnCopiarEnlaceMenu" target="_blank" download>
                                        Copiar enlace
                                    </a>
                                </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>
    <script type="application/javascript">
        @if(session('loggedin'))
            $(document).ready(function(){
                swal("Bienvenido", "Acceso correcto al adminsitrador de UKI&reg;", "success").then(() => {
                    revisarpedidos();
                });
            });
        @endif

        $(document).ready(function(){
            $(".btnCopiarEnlace").click(function(){
                var $temp = $("<input>");
                $("body").append($temp);
                var info_copiar = "{{route('food.restaurante.show', $negocio->slugOrId())}}";
                $temp.val( info_copiar ).select();
                document.execCommand("copy");
                $temp.remove();

                toastr.remove();
                toastr.options.positionClass = "toast-bottom-right";
                toastr.success('Se ha copiado la información en el portapapeles');
                return false;
            });
            $(".btnCopiarEnlaceMenu").click(function(){
                var $temp = $("<input>");
                $("body").append($temp);
                var info_copiar = "{{route('food.restaurante.menu.show', $negocio->slugOrId())}}";
                $temp.val( info_copiar ).select();
                document.execCommand("copy");
                $temp.remove();

                toastr.remove();
                toastr.options.positionClass = "toast-bottom-right";
                toastr.success('Se ha copiado la información en el portapapeles');
                return false;
            });
        });


    </script>
@endsection