routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('food.home'));
});

Route::get('/admin',  function () {
    return redirect(route('admin.dashboard'));
})->name('admin')->middleware('auth', 'verified');

//favor especial para vale
Route::get('/vale_semaforo/{quien}/{respuesta}', '\App\Http\Controllers\Auth\LoginController@vale_semaforo');


Auth::routes(['verify' => true]);
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('/images/public/{path}/{filename}', 'ImagesController@public_image')->name('images.public');
Route::get('/facturas/{id}/pagar', 'FacturacionController@pagarFactura')->name('facturas.pago')->middleware('auth', 'verified');
Route::get('/facturas/{id}/procesar_pago_879827365', 'FacturacionController@procesarPago')->name('facturas.procesar_pago');
Route::middleware('auth', 'verified')->get('/archivos_negocio/{path}/{filename}', 'FilesController@negocio_private_file')->name('files.negocio');

/**
 * ADMIN
 */
Route::middleware('cache.headers:no_cache,private,max_age='.env('CACHE_TIME_BACK', '60').';etag')->middleware('auth', 'verified')->prefix('admin')->name('admin.')->group(function () {
    Route::get('/dashboard', 'Admin\AdminController@index')
        ->name('dashboard');
    Route::resource('horarios', 'Admin\HorariosController');
    Route::resource('negocios', 'Admin\NegociosController');
    Route::get('negocios/{id}/configurar_envios', 'Admin\NegociosController@envios')
        ->name('negocios.envios.edit');
    Route::put('negocios/{id}/configurar_envios', 'Admin\NegociosController@envios_update')
        ->name('negocios.envios.update');
    Route::put('negocios/{id}/slug_update', 'Admin\NegociosController@slug_update')
        ->name('negocios.slug.update');
    Route::put('negocios/{id}/configurar_tiempo', 'Admin\NegociosController@tiempo_update')
        ->name('negocios.tiempo.update');
    Route::get('negocios/{id}/borrar_tiempo', 'Admin\NegociosController@tiempo_delete')
        ->name('negocios.tiempo.delete');
    Route::get('negocios/{id}/configurar_pago', 'Admin\NegociosController@pago_edit')
        ->name('negocios.pago.edit');
    Route::put('negocios/{id}/configurar_pago', 'Admin\NegociosController@pago_update')
        ->name('negocios.pago.update');
    Route::get('negocios/{id}/configurar_categorias', 'Admin\NegociosController@categorias_edit')
        ->name('restaurantes.categorias.edit');
    Route::put('negocios/{id}/configurar_categorias', 'Admin\NegociosController@categorias_update')
        ->name('restaurantes.categorias.update');
    Route::get('negocios/{id}/configurar_notificaciones', 'Admin\NegociosController@notificaciones_edit')
        ->name('negocios.notificaciones.edit');
    Route::put('negocios/{id}/configurar_notificaciones', 'Admin\NegociosController@notificaciones_update')
        ->name('negocios.notificaciones.update');

    //sucursales
    Route::get('negocios/{id}/sucursales', 'Admin\SucursalesController@index')
        ->name('negocios.sucursales.index');
    Route::get('negocios/{id}/sucursales/create', 'Admin\SucursalesController@create')
        ->name('negocios.sucursales.create');
    Route::post('negocios/{id}/sucursales/create', 'Admin\SucursalesController@store')
        ->name('negocios.sucursales.store');
    Route::post('negocios/{id}/sucursales/{sucursal_id}/select', 'Admin\SucursalesController@select')
        ->name('negocios.sucursales.select');
    Route::post('negocios/{id}/sucursales/select', 'Admin\SucursalesController@select_sucursal')
        ->name('negocios.sucursales.selectsucursal');

    Route::get('pedidos', 'Admin\PedidosController@index')
        ->name('pedidos.index');
    Route::get('pedidos/{id}/actualizar_status/{status}', 'Admin\PedidosController@actualizar_status')
        ->name('pedidos.update_status');
    Route::post('pedidos/{id}/actualizar_status/{status}', 'Admin\PedidosController@actualizar_status')
        ->name('pedidos.update_status');
    Route::get('pedidos/historial', 'Admin\PedidosController@historial')->name('pedidos.historial');
    Route::get('pedidos/historial_detallado', 'Admin\PedidosController@historial_detallado')->name('pedidos.historial_detallado');

    //perfil
    Route::get('perfil', 'Admin\PerfilController@edit')->name('perfil.edit');
    Route::put('perfil', 'Admin\PerfilController@update')->name('perfil.update');

    /*
     * Restaurantes
     * */

    Route::resource('categorias-de-platillos', 'Admin\Restaurantes\PlatillocategoriasController')->names([
        'index' => 'platillocategorias.index',
        'create' => 'platillocategorias.create',
        'store' => 'platillocategorias.store',
        'show' => 'platillocategorias.show',
        'edit' => 'platillocategorias.edit',
        'update' => 'platillocategorias.update',
        'destroy' => 'platillocategorias.destroy',
    ]);
    Route::get('categorias-de-platillos/{id}/order/{action}', 'Admin\Restaurantes\PlatillocategoriasController@order')
        ->name('platillocategorias.order');
    Route::resource('platillos', 'Admin\Restaurantes\PlatillosController');
    Route::get('platillos/{id}/order/{action}', 'Admin\Restaurantes\PlatillosController@order')
        ->name('platillos.order');
    Route::resource('operadores', 'Admin\OperadoresController');
    Route::resource('facturas', 'Admin\FacturasController');
    Route::get('facturas/{id}/desglose', 'Admin\FacturasController@bajar_desglose')
        ->name('facturas.desglose');
    Route::resource('tutoriales', 'Admin\TutorialesController');

    /*
     * Facturas
     */
    Route::get('/facturas/{id}/solicitar_factura', 'FacturacionController@solicitarFactura')->name('facturas.solicitar_factura');
});

/**
 * SUPERADMIN
 */

Route::middleware('cache.headers:no_cache,private,max_age='.env('CACHE_TIME_BACK', '60').';etag')->middleware('auth', 'verified')->prefix('superadmin')->name('superadmin.')->group(function () {
    Route::get('/superadmin/negocios', 'Admin\NegociosController@index')->name('negocios.index');
    Route::get('/superadmin/negocios/solicitudes', 'Admin\NegociosController@solicitudes')->name('negocios.solicitudes');
    Route::get('/superadmin/negocios/{id}/verificar', 'Admin\NegociosController@verificar')->name('negocios.verificar');
    Route::resource('regiones', 'Admin\RegionesController');
    Route::get('/pedidos/historial_superadmin', 'Admin\PedidosController@historial_admin')->name('pedidos.historial_superadmin');
});



/**
 *  UKI Food
 */
Route::middleware('cache.headers:no_cache,private,max_age='.env('CACHE_TIME_FRONT', '60').';etag')->prefix('food')->name('food.')->group(function () {
    Route::get('/', '\App\Http\Controllers\Food\DirectoryController@index')->name('home');
    Route::middleware(\App\Http\Middleware\NeedsLocation::class)->get('/categorias/{id}', '\App\Http\Controllers\Food\DirectoryController@categoriaListado')->name('categoria.show');
    Route::middleware(\App\Http\Middleware\NeedsLocation::class)->get('/restaurantes/buscar', '\App\Http\Controllers\Food\DirectoryController@buscar')->name('restaurante.search');
    Route::get('/restaurantes/{id}', '\App\Http\Controllers\Food\DirectoryController@restauranteListado')->name('restaurante.show');
    Route::get('/restaurantes/menu/{id}', '\App\Http\Controllers\Food\DirectoryController@menuOnline')->name('restaurante.menu.show');
    Route::middleware(\App\Http\Middleware\NeedsLocation::class)->get('/platillos/{id}', '\App\Http\Controllers\Food\DirectoryController@platilloDetalle')->name('platillo.show');
    Route::get('/platillos/{id}/{itemId}', '\App\Http\Controllers\Food\DirectoryController@platilloEdit')->name('platillo.edit');
    Route::get('/perfil/region/{region_id}', '\App\Http\Controllers\Food\PerfilController@configurarRegion')->name('perfil.region.update');
    Route::get('/perfil/ubicacion/{lat}/{lon}', '\App\Http\Controllers\Food\PerfilController@configurarUbicacion')->name('perfil.ubicacion.update');
    Route::get('/buscar-direccion/{lat}/{lon}', '\App\Http\Controllers\Food\PerfilController@searchAdress')->name('perfil.ubicacion.buscar');
    Route::get('/perfil', '\App\Http\Controllers\Food\PerfilController@edit')->name('perfil.edit');
    Route::put('/perfil', '\App\Http\Controllers\Food\PerfilController@update')->name('perfil.update');
    Route::get('perfil/comparte_ubicacion', '\App\Http\Controllers\Food\PerfilController@editLocation')->name('perfil.location.edit');

    /**
     * Cart
     */
    Route::post('/carrito/restaurante/{id}/items', '\App\Http\Controllers\Food\CarritoController@add')->name('cart.items.add');
    Route::put('/carrito/restaurante/{id}/items/{item_id}', '\App\Http\Controllers\Food\CarritoController@update')->name('cart.items.update');
    Route::get('/carrito/restaurante/{negocio_id}/items/{item_id}/eliminar', '\App\Http\Controllers\Food\CarritoController@delete')->name('cart.items.delete');
    Route::post('/carrito', '\App\Http\Controllers\Food\CarritoController@procesar')->name('cart.process');
    Route::post('/confirmar', '\App\Http\Controllers\Food\CarritoController@confirmar')->name('cart.confirm');
    Route::get('/carrito', '\App\Http\Controllers\Food\CarritoController@index')->name('cart.show');
    Route::get('/carrito/vaciar', '\App\Http\Controllers\Food\CarritoController@clear')->name('cart.clear');

    Route::get('/pedido/{id}', '\App\Http\Controllers\Food\CarritoController@seguimiento_pedido')->name('pedido.seguimiento');
    //Route::get('pedidos/{id}/entregado', 'Admin\PedidosController@actualizar_status_front')

app/Models/Restaurantes/Item.php
<?php

namespace App\Models\Restaurantes;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    protected $table = "restaurante_pedido_items";

    protected $guarded = ['created_at', 'updated_at'];

    protected $casts = [
        'personalizacion' => 'object'
    ];

    public function pedido()
    {
        return $this->belongsTo('App\Models\Pedido', 'pedido_id');
    }

    public function platillo_data()
    {
        return Platillo::where('nombre',$this->platillo)->where('negocio_id', $this->pedido->negocio->id)->first();
    }

}

app/Http/Controllers/Admin/Restaurantes/PlatillocategoriasController.php
<?php

namespace App\Http\Controllers\Admin\Restaurantes;

use App\Http\Controllers\Admin\AdminBaseController;
use App\Http\Requests\Restaurantes\PlatillocategoriaStore;
use App\Http\Requests\Restaurantes\PlatillocategoriaUpdate;
use App\Models\Restaurantes\Platillo;
use App\Models\Restaurantes\Platillocategoria;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;

class PlatillocategoriasController extends AdminBaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\View
     */
    public function index()
    {
        Platillocategoria::setNewOrder(Platillocategoria::getAllIds($this->_negocio->id));
        $categorias = Platillocategoria::ordered()->where('negocio_id', '=', $this->_negocio->id)->get();
        $viewdata = [
            'categorias' => $categorias
        ];
        return view('admin.restaurantes.platillocategorias.listado', $viewdata);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\View
     */
    public function create()
    {
        $categoria = new Platillocategoria();
        $viewdata = [
            'titulo' => 'Agregar categoría',
            'callToAction' => 'Agregar',
            'categoria' => $categoria,
            'route' => route('admin.platillocategorias.store'),
        ];
        return view('admin.restaurantes.platillocategorias.formulario', $viewdata);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PlatillocategoriaStore $request)
    {
        $data = $request->except('_token, _method','foto');
        $data['negocio_id'] = $this->_negocio->id;
        $categoria = Platillocategoria::create($data);

        if ($request->hasFile('foto')) {
            $image      = $request->file('foto');
            $nombreArchivo   = "categoria{$categoria->id}_". time() . '.' . $image->getClientOriginalExtension();

            $img = Image::make($image->getRealPath());
            $img->resize(600, 600, function ($constraint) {
                $constraint->aspectRatio();
            });
            $img->stream();

            Storage::delete("public/restaurantes/platillocategorias/{$categoria->foto}");

            Storage::disk('local')->put('public/restaurantes/platillocategorias/'.$nombreArchivo, $img);
            $categoria->foto = $nombreArchivo;
            $categoria->save();
        }

        if(Auth::user()->tipo == 'superadmin' || (Auth::user()->negocio && Auth::user()->negocio->verificado)) {
            $mensajeFlash['mensaje'] = "Categoría {$categoria->nombre} creada correctamente";
        } else {
            $mensajeFlash['mensaje'] = "Categoría {$categoria->nombre} creada correctamente. Accede al dashboard para verificar qué información falta a tu restaruante";
        }
        $mensajeFlash['titulo'] = 'Todo bien';
        $mensajeFlash['accion'] = 'success';
        $request->session()->flash('mensajeFlash', $mensajeFlash);

        return redirect(route('admin.platillocategorias.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Restaurantes\Platillocategoria  $platillocategoria
     * @return \Illuminate\Http\Response
     */
    public function show(Platillocategoria $platillocategoria)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Restaurantes\Platillocategoria  $platillocategoria
     * @return \Illuminate\Contracts\View\View
     */
    public function edit($platillocategoria_id)
    {
        $categoria = Platillocategoria::findOrFail($platillocategoria_id);
        $viewdata = [
            'titulo' => 'Editar categoría',
            'callToAction' => 'Guardar',
            'categoria' => $categoria,
            'route' => route('admin.platillocategorias.update', $categoria->id),
        ];
        return view('admin.restaurantes.platillocategorias.formulario', $viewdata);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Restaurantes\Platillocategoria  $platillocategoria
     * @return \Illuminate\Http\Response
     */
    public function update(PlatillocategoriaUpdate $request, $platillocategoria_id)
    {
        $categoria = Platillocategoria::findOrFail($platillocategoria_id);
        $data = $request->except('_token, _method','foto');
        $categoria->update($data);

        if ($request->hasFile('foto')) {
            $image      = $request->file('foto');
            $nombreArchivo   = "categoria{$categoria->id}_". time() . '.' . $image->getClientOriginalExtension();

            $img = Image::make($image->getRealPath());
            $img->resize(600, 600, function ($constraint) {
                $constraint->aspectRatio();
            });
            $img->stream();

            Storage::delete("public/restaurantes/platillocategorias/{$categoria->foto}");

            Storage::disk('local')->put('public/restaurantes/platillocategorias/'.$nombreArchivo, $img);
            $categoria->foto = $nombreArchivo;
            $categoria->save();
        }

        $mensajeFlash['titulo'] = 'Todo bien';
        $mensajeFlash['mensaje'] = "Categoría {$categoria->nombre} actualizada correctamente";
        $mensajeFlash['accion'] = 'success';
        $request->session()->flash('mensajeFlash', $mensajeFlash);

        return redirect(route('admin.platillocategorias.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Restaurantes\Platillocategoria  $platillocategoria
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $platillocategoria_id)
    {
        $categoria = Platillocategoria::findOrFail($platillocategoria_id);
        $categoria->delete();

        $mensajeFlash['titulo'] = 'Todo bien';
        $mensajeFlash['mensaje'] = "Categoría eliminada correctamente";
        $mensajeFlash['accion'] = 'success';
        $request->session()->flash('mensajeFlash', $mensajeFlash);

        return redirect(route('admin.platillocategorias.index'));
    }

    public function order(Request $request, $categoria_id, $action) {
        $categoria = Platillocategoria::findOrFail($categoria_id);

        switch ($action) {
            case 'up': $categoria->moveOrderUp(); break;
            case 'down': $categoria->moveOrderDown(); break;
        }

        $mensajeFlash['titulo'] = 'Todo bien';
        $mensajeFlash['mensaje'] = "Categoría {$categoria->nombre} actualizada correctamente";
        $mensajeFlash['accion'] = 'success';
        $request->session()->flash('mensajeFlash', $mensajeFlash);

        return redirect(route('admin.platillocategorias.index'));
    }
}

resources/views/admin/restaurantes/platillocategorias/formulario.blade.php
@extends('layouts.app')

@section('content')
    <div  class="row">
        <div  class="col-md-12">
            <nav  aria-label="breadcrumb">
                <ol  class="breadcrumb pl-0">
                    <li  class="breadcrumb-item">
                        <a  href="{{route('admin')}}"><i class="material-icons">home</i> Inicio</a>
                    </li>
                    <li  class="breadcrumb-item"><a  href="#">Menú</a></li>
                    <li  class="breadcrumb-item">
                        <a  href="{{route('admin.platillocategorias.index')}}">Categorías de Platillos</a>
                    </li>
                    <li  aria-current="page" class="breadcrumb-item active">{{$categoria->id?"Editar":"Agregar"}}</li>
                </ol>
            </nav>
        </div>
        <div  class="ms-panel col-md-8">
            <div  class="ms-panel-header">
                <div class="d-flex justify-content-between">
                    <div class="align-self-center align-left">
                        <h6 >{{$titulo}}</h6>
                    </div>
                    <a href="{{route('admin.platillocategorias.index')}}"><i class="material-icons">arrow_back</i> Regresar</a>
                </div>
            </div>
            <div  class="ms-panel-body">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul style="margin: 0px;">
                            @foreach ($errors->all() as $error)
                                <li><i class="flaticon-alert"></i> {{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <form method="POST" action="{{$route}}" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    {{$categoria->id?method_field('put'):method_field('post')}}
                    <p style="text-align: center">
                        @if($categoria->foto)
                            <img class="img-fluid img-detail" src="{{route('images.public', [base64_encode('restaurantes/platillocategorias/'), $categoria->foto])}}"/>
                        @else
                            <img class="img-fluid img-detail" src="{{URL::to('/assets/img')}}/sin_imagen.jpg"/>
                        @endif
                    </p>
                    <div class="form-group">
                        <label for="nombre">Nombre</label>
                        <input type="text" class="form-control @error('nombre') is-invalid @enderror" id="nombre" name="nombre" placeholder="Nombre de la categoría" value="{{old('nombre')?old('nombre'):$categoria->nombre}}">
                    </div>
                    <div class="form-group">
                        <label for="descripcion">Descripción</label>
                        <textarea class="form-control text-counter @error('descripcion') is-invalid @enderror" id="descripcion"
                                  name="descripcion" rows="3" placeholder="Descripción de esta categoría"
                                  maxlength="250">{{old('descripcion')?old('descripcion'):$categoria->descripcion}}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="foto">Cambiar imagen <small> (PNG, JPG | max. 1 MB | recomendado 1024 x 768)</small></label>
                        <input type="file" class="form-control @error('foto') is-invalid @enderror" id="foto" name="foto" />
                    </div>
                    @if(auth::user()->tipo != 'operador')
                        <input type="submit" class="btn btn-primary" value="{{$callToAction}}">
                    @endif
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/restaurantes/platillocategorias/listado.blade.php
@extends('layouts.app')

@section('content')
    <div _ngcontent-vbt-c44="" class="row">
        <div _ngcontent-vbt-c44="" class="col-md-12">
            <nav _ngcontent-vbt-c44="" aria-label="breadcrumb">
                <ol _ngcontent-vbt-c44="" class="breadcrumb pl-0">
                    <li _ngcontent-vbt-c44="" class="breadcrumb-item"><a _ngcontent-vbt-c44="" href="{{route('admin')}}"><i
                                _ngcontent-vbt-c44="" class="material-icons">home</i> Inicio</a></li>
                    <li _ngcontent-vbt-c44="" class="breadcrumb-item"><a _ngcontent-vbt-c44="" href="#">Menú</a></li>
                    <li _ngcontent-vbt-c44="" aria-current="page" class="breadcrumb-item active">Categorías de Platillos</li>
                </ol>
            </nav>
        </div>
        <div _ngcontent-vbt-c51="" class="ms-panel col-md-12">
            <div _ngcontent-vbt-c51="" class="ms-panel-header">
                <div class="d-flex justify-content-between">
                    <div class="align-self-center align-left">
                        <h6 _ngcontent-vbt-c51="">Categorías de platillos</h6>
                    </div>
                    <a href="{{route('admin.platillocategorias.create')}}" class="btn text-white btn-info" ><i class="material-icons">add</i> Nueva Categoría</a>
                </div>
            </div>
            <div _ngcontent-vbt-c51="" class="ms-panel-body">
            @if($categorias->count() > 0)
                <div class="table-responsive">
                    <table id="example" class="table table-sm table-datatable table-striped thead-primary w-100 dataTable no-footer" style="width: 100%;"style="width:100%">
                    <thead >
                        <tr>
                            <th style="width: 220px;">Foto</th>
                            <th>Nombre</th>
                            <th style="width: 40%">Descripción</th>
                            <th>Posición</th>
                            <th style="width: 160px;">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($categorias as $categoria)
                            <tr>
                                <td style="width: 220px;">
                                    @if($categoria->foto)
                                        <img class="table-img-lg" src="{{route('images.public', [base64_encode('restaurantes/platillocategorias/'), $categoria->foto])}}"/>
                                    @else
                                        <img class="table-img-lg" src="{{URL::to('/assets/img')}}/sin_imagen.jpg"/>
                                    @endif
                                </td>
                                <td>{{$categoria->nombre}}</td>
                                <td><span style="white-space: pre-wrap;">{{$categoria->descripcion}}</span></td>
                                <td>
                                    @if(!$categoria->isFirstInOrder())
                                        <a href="{{route('admin.platillocategorias.order', [$categoria->id, 'up'])}}"><i class="fa fa-arrow-up"></i></a>
                                    @endif
                                        @if(!$categoria->isLastInOrder())
                                            <a href="{{route('admin.platillocategorias.order', [$categoria->id, 'down'])}}"><i class="fa fa-arrow-down"></i></a>
                                    @endif
                                </td>
                                <td>
                                    <a href="{{route('admin.platillocategorias.edit', $categoria->id)}}" class="btn  text-white btn-info"><i class="flaticon-pencil"></i> Editar</a>
                                    &nbsp;
                                    <a class="btn btnEliminar text-white btn-danger" data-delete-id="{{$categoria->id}}"><i class="flaticon-trash"></i> Borrar</a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                </div>
            @endif
                @if($categorias->count() <= 0)
                    <p class="alert alert-info"><i class="flaticon-information"></i> Aún no se han dado de alta categorías de platillos</p>
                @endif
            </div>
        </div>
    </div>
    <div class="delete_form">
        <form id="deleteForm" method="POST" action="" >
            {{ csrf_field() }}
            {{method_field('delete')}}
        </form>
    </div>
    <script type="application/javascript">
        $(document).ready(function() {
            $('.table-datatable').DataTable({"ordering": false, "pageLength": 25, "bLengthChange": false,
                "language": {
                    "url": "{{URL::to('/assets/lang/dataTable/Spanish.json')}}"
                }});

            $('.btnEliminar').click(function(){
                const borrarId = $(this).data('deleteId');
                Swal.fire({
                    title: '¿Estás seguro que deseas borrar este elemento?',
                    text: "No podrás revertir esta acción",
                    type: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#d33',
                    cancelButtonColor: '#666',
                    confirmButtonText: 'Sí, quiero eliminarlo'
                }).then(function (result) {
                    if (result.value) {
                        $('#deleteForm').attr('action', '{{route('admin.platillocategorias.index')}}' + '/' + borrarId);
                        $('#deleteForm').submit();
                    }
                });
            });
        } );
    </script>
@endsection