routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('food.home'));
});

Route::get('/admin',  function () {
    return redirect(route('admin.dashboard'));
})->name('admin')->middleware('auth', 'verified');

//favor especial para vale
Route::get('/vale_semaforo/{quien}/{respuesta}', '\App\Http\Controllers\Auth\LoginController@vale_semaforo');


Auth::routes(['verify' => true]);
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('/images/public/{path}/{filename}', 'ImagesController@public_image')->name('images.public');
Route::get('/facturas/{id}/pagar', 'FacturacionController@pagarFactura')->name('facturas.pago')->middleware('auth', 'verified');
Route::get('/facturas/{id}/procesar_pago_879827365', 'FacturacionController@procesarPago')->name('facturas.procesar_pago');
Route::middleware('auth', 'verified')->get('/archivos_negocio/{path}/{filename}', 'FilesController@negocio_private_file')->name('files.negocio');

/**
 * ADMIN
 */
Route::middleware('cache.headers:no_cache,private,max_age='.env('CACHE_TIME_BACK', '60').';etag')->middleware('auth', 'verified')->prefix('admin')->name('admin.')->group(function () {
    Route::get('/dashboard', 'Admin\AdminController@index')
        ->name('dashboard');
    Route::resource('horarios', 'Admin\HorariosController');
    Route::resource('negocios', 'Admin\NegociosController');
    Route::get('negocios/{id}/configurar_envios', 'Admin\NegociosController@envios')
        ->name('negocios.envios.edit');
    Route::put('negocios/{id}/configurar_envios', 'Admin\NegociosController@envios_update')
        ->name('negocios.envios.update');
    Route::put('negocios/{id}/slug_update', 'Admin\NegociosController@slug_update')
        ->name('negocios.slug.update');
    Route::put('negocios/{id}/configurar_tiempo', 'Admin\NegociosController@tiempo_update')
        ->name('negocios.tiempo.update');
    Route::get('negocios/{id}/borrar_tiempo', 'Admin\NegociosController@tiempo_delete')
        ->name('negocios.tiempo.delete');
    Route::get('negocios/{id}/configurar_pago', 'Admin\NegociosController@pago_edit')
        ->name('negocios.pago.edit');
    Route::put('negocios/{id}/configurar_pago', 'Admin\NegociosController@pago_update')
        ->name('negocios.pago.update');
    Route::get('negocios/{id}/configurar_categorias', 'Admin\NegociosController@categorias_edit')
        ->name('restaurantes.categorias.edit');
    Route::put('negocios/{id}/configurar_categorias', 'Admin\NegociosController@categorias_update')
        ->name('restaurantes.categorias.update');
    Route::get('negocios/{id}/configurar_notificaciones', 'Admin\NegociosController@notificaciones_edit')
        ->name('negocios.notificaciones.edit');
    Route::put('negocios/{id}/configurar_notificaciones', 'Admin\NegociosController@notificaciones_update')
        ->name('negocios.notificaciones.update');

    //sucursales
    Route::get('negocios/{id}/sucursales', 'Admin\SucursalesController@index')
        ->name('negocios.sucursales.index');
    Route::get('negocios/{id}/sucursales/create', 'Admin\SucursalesController@create')
        ->name('negocios.sucursales.create');
    Route::post('negocios/{id}/sucursales/create', 'Admin\SucursalesController@store')
        ->name('negocios.sucursales.store');
    Route::post('negocios/{id}/sucursales/{sucursal_id}/select', 'Admin\SucursalesController@select')
        ->name('negocios.sucursales.select');
    Route::post('negocios/{id}/sucursales/select', 'Admin\SucursalesController@select_sucursal')
        ->name('negocios.sucursales.selectsucursal');

    Route::get('pedidos', 'Admin\PedidosController@index')
        ->name('pedidos.index');
    Route::get('pedidos/{id}/actualizar_status/{status}', 'Admin\PedidosController@actualizar_status')
        ->name('pedidos.update_status');
    Route::post('pedidos/{id}/actualizar_status/{status}', 'Admin\PedidosController@actualizar_status')
        ->name('pedidos.update_status');
    Route::get('pedidos/historial', 'Admin\PedidosController@historial')->name('pedidos.historial');
    Route::get('pedidos/historial_detallado', 'Admin\PedidosController@historial_detallado')->name('pedidos.historial_detallado');

    //perfil
    Route::get('perfil', 'Admin\PerfilController@edit')->name('perfil.edit');
    Route::put('perfil', 'Admin\PerfilController@update')->name('perfil.update');

    /*
     * Restaurantes
     * */

    Route::resource('categorias-de-platillos', 'Admin\Restaurantes\PlatillocategoriasController')->names([
        'index' => 'platillocategorias.index',
        'create' => 'platillocategorias.create',
        'store' => 'platillocategorias.store',
        'show' => 'platillocategorias.show',
        'edit' => 'platillocategorias.edit',
        'update' => 'platillocategorias.update',
        'destroy' => 'platillocategorias.destroy',
    ]);
    Route::get('categorias-de-platillos/{id}/order/{action}', 'Admin\Restaurantes\PlatillocategoriasController@order')
        ->name('platillocategorias.order');
    Route::resource('platillos', 'Admin\Restaurantes\PlatillosController');
    Route::get('platillos/{id}/order/{action}', 'Admin\Restaurantes\PlatillosController@order')
        ->name('platillos.order');
    Route::resource('operadores', 'Admin\OperadoresController');
    Route::resource('facturas', 'Admin\FacturasController');
    Route::get('facturas/{id}/desglose', 'Admin\FacturasController@bajar_desglose')
        ->name('facturas.desglose');
    Route::resource('tutoriales', 'Admin\TutorialesController');

    /*
     * Facturas
     */
    Route::get('/facturas/{id}/solicitar_factura', 'FacturacionController@solicitarFactura')->name('facturas.solicitar_factura');
});

/**
 * SUPERADMIN
 */

Route::middleware('cache.headers:no_cache,private,max_age='.env('CACHE_TIME_BACK', '60').';etag')->middleware('auth', 'verified')->prefix('superadmin')->name('superadmin.')->group(function () {
    Route::get('/superadmin/negocios', 'Admin\NegociosController@index')->name('negocios.index');
    Route::get('/superadmin/negocios/solicitudes', 'Admin\NegociosController@solicitudes')->name('negocios.solicitudes');
    Route::get('/superadmin/negocios/{id}/verificar', 'Admin\NegociosController@verificar')->name('negocios.verificar');
    Route::resource('regiones', 'Admin\RegionesController');
    Route::get('/pedidos/historial_superadmin', 'Admin\PedidosController@historial_admin')->name('pedidos.historial_superadmin');
});



/**
 *  UKI Food
 */
Route::middleware('cache.headers:no_cache,private,max_age='.env('CACHE_TIME_FRONT', '60').';etag')->prefix('food')->name('food.')->group(function () {
    Route::get('/', '\App\Http\Controllers\Food\DirectoryController@index')->name('home');
    Route::middleware(\App\Http\Middleware\NeedsLocation::class)->get('/categorias/{id}', '\App\Http\Controllers\Food\DirectoryController@categoriaListado')->name('categoria.show');
    Route::middleware(\App\Http\Middleware\NeedsLocation::class)->get('/restaurantes/buscar', '\App\Http\Controllers\Food\DirectoryController@buscar')->name('restaurante.search');
    Route::get('/restaurantes/{id}', '\App\Http\Controllers\Food\DirectoryController@restauranteListado')->name('restaurante.show');
    Route::get('/restaurantes/menu/{id}', '\App\Http\Controllers\Food\DirectoryController@menuOnline')->name('restaurante.menu.show');
    Route::middleware(\App\Http\Middleware\NeedsLocation::class)->get('/platillos/{id}', '\App\Http\Controllers\Food\DirectoryController@platilloDetalle')->name('platillo.show');
    Route::get('/platillos/{id}/{itemId}', '\App\Http\Controllers\Food\DirectoryController@platilloEdit')->name('platillo.edit');
    Route::get('/perfil/region/{region_id}', '\App\Http\Controllers\Food\PerfilController@configurarRegion')->name('perfil.region.update');
    Route::get('/perfil/ubicacion/{lat}/{lon}', '\App\Http\Controllers\Food\PerfilController@configurarUbicacion')->name('perfil.ubicacion.update');
    Route::get('/buscar-direccion/{lat}/{lon}', '\App\Http\Controllers\Food\PerfilController@searchAdress')->name('perfil.ubicacion.buscar');
    Route::get('/perfil', '\App\Http\Controllers\Food\PerfilController@edit')->name('perfil.edit');
    Route::put('/perfil', '\App\Http\Controllers\Food\PerfilController@update')->name('perfil.update');
    Route::get('perfil/comparte_ubicacion', '\App\Http\Controllers\Food\PerfilController@editLocation')->name('perfil.location.edit');

    /**
     * Cart
     */
    Route::post('/carrito/restaurante/{id}/items', '\App\Http\Controllers\Food\CarritoController@add')->name('cart.items.add');
    Route::put('/carrito/restaurante/{id}/items/{item_id}', '\App\Http\Controllers\Food\CarritoController@update')->name('cart.items.update');
    Route::get('/carrito/restaurante/{negocio_id}/items/{item_id}/eliminar', '\App\Http\Controllers\Food\CarritoController@delete')->name('cart.items.delete');
    Route::post('/carrito', '\App\Http\Controllers\Food\CarritoController@procesar')->name('cart.process');
    Route::post('/confirmar', '\App\Http\Controllers\Food\CarritoController@confirmar')->name('cart.confirm');
    Route::get('/carrito', '\App\Http\Controllers\Food\CarritoController@index')->name('cart.show');
    Route::get('/carrito/vaciar', '\App\Http\Controllers\Food\CarritoController@clear')->name('cart.clear');

    Route::get('/pedido/{id}', '\App\Http\Controllers\Food\CarritoController@seguimiento_pedido')->name('pedido.seguimiento');
    //Route::get('pedidos/{id}/entregado', 'Admin\PedidosController@actualizar_status_front')

app/Http/Controllers/Food/DirectoryController.php
<?php

namespace App\Http\Controllers\Food;

use App\Http\Controllers\Controller;
use App\Models\Food\Perfil;
use App\Models\Negocio;
use App\Models\Region;
use App\Models\Restaurantes\Platillo;
use App\Models\Restaurantes\Restaurantecategoria;
use Melihovv\ShoppingCart\Facades\ShoppingCart;
use Illuminate\Http\Request;

class DirectoryController extends Controller
{
    public function index(Request $request)
    {
        if (env('MANTENIMIENTO', null) == 'true' ) {
            return redirect('https://restaurantes.uki.mx');
        }

        $categorias = Restaurantecategoria::all();
        $perfil = Perfil::getPerfil($request);

        $restaurantes = Negocio::top($perfil);

        $regiones = Region::all();
        $viewdata = [
            'categorias' => $categorias,
            'perfil' => $perfil,
            'regiones' => $regiones,
            'restaurantes' => $restaurantes,
        ];
        return view('food.home', $viewdata);
    }

    public function categoriaListado(Request $request, $categoria_id)
    {
        $categoria = Restaurantecategoria::findOrFail($categoria_id);
        $perfil = Perfil::getPerfil($request);
        $viewdata = [
            'categoria' => $categoria,
            'perfil' => $perfil,
        ];
        return view('food.categoria', $viewdata);
    }

    public function restauranteListado(Request $request, $restaurante_id)
    {
        //Revisando slug
        $restaurante = Negocio::findSlugOrId($restaurante_id);

        if (!$restaurante->esta_habilitado()) {
            $mensajeFlash['titulo'] = 'Error';
            $mensajeFlash['mensaje'] = "Este restaurante no está disponible en este momento por alguna razón.";
            $mensajeFlash['accion'] = 'alert-danger';
            $request->session()->flash('mensajeFlash', $mensajeFlash);
            return redirect(route('food.home'));
        }

        $perfil = Perfil::getPerfil($request);
        $lastrestaurante = null;
        $cartcount = 0;
        if ($request->session()->get('last-cart-instance')){
            ShoppingCart::instance($request->session()->get('last-cart-instance'))->restore(session()->getId());
            $lastrestaurante = Negocio::find($request->session()->get('last-cart-instance'));
            $cartcount = ShoppingCart::instance($request->session()->get('last-cart-instance'))->count();
        }

        //obteniendo distancia
        $restaurante->getDistancia($perfil->lat, $perfil->lon);

        $viewdata = [
            'restaurante' => $restaurante,
            'lastrestaurante' => $lastrestaurante,
            'cartcount' => $cartcount,
            'perfil' => $perfil,
        ];
        return view('food.restaurante', $viewdata);
    }

    public function menuOnline(Request $request, $restaurante_id)
    {
        //Revisando slug
        $restaurante = Negocio::findSlugOrId($restaurante_id);

        if ($restaurante->adeudo) {
            $mensajeFlash['titulo'] = 'Error';
            $mensajeFlash['mensaje'] = "Este restaurante no está disponible en este momento por alguna razón.";
            $mensajeFlash['accion'] = 'alert-danger';
            $request->session()->flash('mensajeFlash', $mensajeFlash);
            return redirect(route('food.home'));
        }

        $viewdata = [
            'restaurante' => $restaurante,
        ];
        return view('food.menu_online', $viewdata);
    }

    public function platilloDetalle(Request $request, $platillo_id)
    {
        $platillo = Platillo::findOrFail($platillo_id);

        $viewdata = [
            'platillo' => $platillo,
        ];
        return view('food.platillo', $viewdata);
    }

    public function platilloEdit(Request $request, $platillo_id, $item_id)
    {
        $platillo = Platillo::findOrFail($platillo_id);
        ShoppingCart::instance($platillo->negocio_id)->restore(session()->getId());
        $cartItem = ShoppingCart::get($item_id);

        $viewdata = [
            'platillo' => $platillo,
            'item' => $cartItem,
        ];
        return view('food.platillo', $viewdata);
    }

    public function buscar(Request $request)
    {
        $termino_busqueda = $request->buscar;

        $perfil = Perfil::getPerfil($request);
        $restaurantes = Negocio::buscar($termino_busqueda, $perfil->region_id, true, $perfil->lat, $perfil->lon);

        $viewdata = [
            'restaurantes' => $restaurantes,
            'perfil' => $perfil
        ];
        return view('food.busqueda', $viewdata);
    }
}

resources/views/food/categoria.blade.php
@extends('layouts.food', ['custom_meta' => true])

@section('custom_meta')
    <meta property="og:title" content="{{$categoria->nombre}} en Uki&reg;" />
    <meta property="og:image" content="{{asset("food_assets/images/categorias/{$categoria->foto}")}}" />
    <meta property="og:description" content="Encuentra los mejores restaurantes de {{$categoria->nombre}} a través de Uki&reg;: una plataforma que conecta a los restaurantes con los consumidores de manera trasparente y justa." />
    <meta property="og:url" content="{{route('food.categoria.show', $categoria->id)}}" />
    <title>Uki&reg; @if(env('APP_ENV', 'local') == 'beta') - Beta @endif - {{$categoria->nombre}}</title>
@endsection

@section('content')

@section('content')
    <section class="containerCategoria " style="padding:0px; background-image: url('{{asset("storage/restaurantes/categorias/{$categoria->foto}")}}')">
        <div style="background-color: rgba(0,0,0, .7); padding: 0px; margin: 0px;">
            <div class="container">
                <div class="row">
                    <div class="col col-12">
                        <br/><br/>
                        <h4>{{$categoria->nombre}}</h4>
                        <br/>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <hr/>
    <section id="restaurantecategorias">
        <div class="container">
            <div class="row">
                @if(!($perfil->lat && $perfil->lon))
                    <p class="alert alert-warning"><i class="fa fa-warning"></i> Actualmente se muestran solo restaurantes con servicio de Pickup & Go, para mostrar restaurantes con envio a domicilio <a href="{{route('food.perfil.edit')}}?solo_ubicacion=true">configura tu ubicación</a></p>
                @endif
                @foreach($categoria->restaurantes($perfil->region_id??null, true, $perfil->lat, $perfil->lon ) as $restaurante)
                    @component('food.components.restaurante')
                        @slot('restaurante', $restaurante)
                        @slot('perfil', $perfil)
                    @endcomponent
                @endforeach
            </div>
        </div>
    </section>
    <br/>
@endsection

resources/views/food/home.blade.php
@extends('layouts.food')

@section('content')

    @component('food.components.hero.hero') @endcomponent

    <hr/>
    <section id="restaurantecategorias">
        <div class="container">
            <div class="row">
                @if(isset($perfil))
                    @if(isset($perfil->region_id))
                        @if($perfil->isFarFromRegion())
                            <p class="alert alert-danger"><i class="fa fa-warning"></i> TU DIRECCIÓN ESTÁ LEJOS DE LA ZONA UKI MÁS CERCANA. SOLO PUEDES REALIZAR PEDIDOS PICK UP & GO. <a href="{{route('food.perfil.edit')}}">REVISA QUE TU DIRECCIÓN SEA LA CORRECTA</a></p>
                        @endif
                    @endif
                @endif
                <br/>
                <h4 style="text-align: center">Explora negocios</h4>
                <br class="solo_desktop"/>
                @foreach($restaurantes as $restaurante)
                    @component('food.components.restaurante')
                        @slot('restaurante', $restaurante)
                        @slot('perfil', $perfil)
                    @endcomponent
                @endforeach
            </div>

            <div class="row">
                <h4 style="text-align: center">Explora negocios por categoría</h4>
                <br class="solo_desktop"/>
                @foreach($categorias as $categoria)
                    @if(isset($perfil->region_id) & ($perfil->lat && $perfil->lon))
                        @if(count($categoria->restaurantes($perfil->region_id??null, true, $perfil->lat, $perfil->lon)) > 0)
                            <a href="{{route('food.categoria.show', $categoria->id)}}">
                                <div class="col col-xs-6 col-md-4 col-lg-3 categoria">
                                    <img class="img-fluid" src="{{asset("food_assets/images/categorias/{$categoria->foto}")}}">
                                </div>
                            </a>
                        @endif
                    @else
                        <a href="{{route('food.perfil.location.edit', $categoria->id)}}">
                            <div class="col col-xs-6 col-md-4 col-lg-3 categoria">
                                <img class="img-fluid" src="{{asset("food_assets/images/categorias/{$categoria->foto}")}}">
                            </div>
                        </a>
                    @endif
                @endforeach
            </div>

        </div>
    </section>
    <br/>
    <script type="text/javascript">
        $(document).ready(function(){

        });
    </script>
@endsection

resources/views/food/menu_online.blade.php
@extends('layouts.food', ['custom_meta' => true, 'menu_online' => true])

@section('custom_meta')
    <meta property="og:title" content="{{$restaurante->nombre}} en Uki&reg;" />
    @if($restaurante->logo)
        <meta property="og:image" content="{{route('images.public', [base64_encode('negocios/logos/'), $restaurante->logo])}}" />
    @else
        <meta property="og:image" content="https://uki.mx/assets/img/logo.png" />
    @endif
    <meta property="og:description" content="Disfruta los platillos de {{$restaurante->nombre}} a través de Uki&reg;: una plataforma que conecta a los restaurantes con los consumidores de manera trasparente y justa." />
    <meta property="og:url" content="{{route('food.restaurante.show', $restaurante->id)}}" />
    <title>Uki&reg; @if(env('APP_ENV', 'local') == 'beta') - Beta @endif - {{$restaurante->nombre}}</title>
@endsection

@section('content')
<br/>
    <section>
        <div class="container">
            <div class="row">
                <div class="col col-12">
                    <p style="text-align: center">
                        <a class="img-fluid" href="{{route('food.restaurante.show',$restaurante->id)}}" style="@if(!$restaurante->activo) filter: grayscale(1) @endif">
                            @if($restaurante->logo)
                                <img class="logo-negocio-small" src="{{route('images.public', [base64_encode('negocios/logos/'), $restaurante->logo])}}"/>
                            @else
                                <img class="logo-negocio-small" src="{{URL::to('/assets/img')}}/sin_imagen.jpg"/>
                            @endif
                        </a>
                    </p>
                    <h5 style="text-align: center">{{$restaurante->nombre}}</h5>
                    <div style="text-align: center; font-size: 12px;">

                        <ul class="navbar-nav" id="menu-categorias">
                            @foreach($restaurante->platillo_categorias as $categoria)
                                <li class="nav-item">
                                    <a class="nav-link linkCategoria" href="#{{$categoria->slug()}}">{{$categoria->nombre}} <span class="sr-only">(current)</span></a>
                                </li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <hr/>
    <section id="restaurantecategorias">
        <div class="container">
            @foreach($restaurante->platillo_categorias as $categoria)
                @component('food.components.categoriaRestaurante')
                    @slot('categoria', $categoria)
                    @slot('restaurante', $restaurante)
                    @slot('perfil', null)
                    @slot('menu_online', true)
                @endcomponent
            @endforeach
        </div>
    </section>
    <br/>
<style>
    #menu-categorias {
        z-index: 9;
        background-color: #FFF;
        min-width: 100%;
        left: 0px;
        white-space: nowrap;
        width: 100%;
        overflow: auto;
        padding-right: 30px;
    }
</style>
<script type="text/javascript">
    $(document).ready(function(){

        $("#menu-categorias").sticky({topSpacing:84, zIndex:9999});

        $('.linkCategoria').click(function(){
            var goto = $(this).attr('href');
            $([document.documentElement, document.body]).animate({
                scrollTop: $(goto).offset().top - 140
            }, 600);
            return false;
        });
    });
</script>
@endsection

resources/views/food/pedir_ubicacion.blade.php
@extends('layouts.food')

@section('content')

    @component('food.components.hero.antes_de_continuar')
        @slot('perfil', $perfil)
    @endcomponent
@endsection

resources/views/food/platillo.blade.php
@extends('layouts.food', ['custom_meta' => true])

@section('custom_meta')
    <meta property="og:title" content="{{$platillo->negocio->nombre}} en Uki&reg;" />
    @if($platillo->negocio->logo)
        <meta property="og:image" content="{{route('images.public', [base64_encode('negocios/logos/'), $platillo->negocio->logo])}}" />
    @else
        <meta property="og:image" content="https://uki.mx/assets/img/logo.png" />
    @endif
    <meta property="og:description" content="Disfruta los platillos de {{$platillo->negocio->nombre}} a través de Uki&reg;: una plataforma que conecta a los restaurantes con los consumidores de manera trasparente y justa." />
    <meta property="og:url" content="{{route('food.platillo.show', $platillo->id)}}" />
    <title>Uki&reg; @if(env('APP_ENV', 'local') == 'beta') - Beta @endif - {{$platillo->negocio->nombre}}</title>
@endsection

@section('content')

    <hr/>
    <section id="perfil_usuario">
        <div class="container">
            <form id="frmItem" method="POST"
                  @if(isset($item))
                    action="{{route('food.cart.items.update', [$platillo->negocio_id, $item->getUniqueId()])}}"
                  @else
                    action="{{route('food.cart.items.add', $platillo->negocio_id)}}"
                  @endif
            >
                {{isset($item)?method_field('put'):method_field('post')}}
                {{ csrf_field() }}
                <input type="hidden" name="id" value="{{$platillo->id}}">
                <input type="hidden" name="name" value="{{$platillo->nombre}}">
                <input type="hidden" name="price" value="{{$platillo->precio_final()}}">
                <input id="hdnGoToCheckout" type="hidden" name="goToCheckout" />

                <h3>{{$platillo->nombre}}</h3>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul style="margin: 0px;">
                            @foreach ($errors->all() as $error)
                                <li><i class="flaticon-alert"></i> {{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="row">
                <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
                    <div class="menu-widget m-b-30">
                        <div class="widget-heading">
                            <h3 class="widget-title text-dark">
                                Detalles del platillo
                            </h3>
                            <div class="clearfix"></div>
                        </div>
                        <div class="collapse in" id="1">
                            <div class="food-item white">
                                <div class="row">
                                    <div class="col-md-4">
                                        <img style="width: 350px; max-width:100%; margin-right: 20px;"  src="{{$platillo->foto ? route('images.public', [base64_encode('restaurantes/platillos/'), $platillo->foto]) : URL::to('/assets/img/sin_imagen.jpg')}}" alt="Food logo">
                                        <!-- end:Description -->
                                    </div>
                                    <div class="col-md-8">
                                        <br/>
                                        @component('food.components.platillo.precio')
                                            @slot('platillo', $platillo)
                                            @slot('restaurante', $platillo->negocio)
                                            @slot('botones', false)
                                        @endcomponent
                                        <p>{{$platillo->descripcion}}</p>
                                    </div>
                                </div>
                                <!-- end:row -->
                            </div>
                        </div>
                        <!-- end:Collapse -->
                    </div>
                    <div class="solo_desktop">
                        @if(!isset($item))<button id="btnGoToCheckout" style="margin-bottom: 8px;" type="button" class="btn theme-btn btn-lg"> Agregar e ir a pagar</button><br/>@endif
                        <button style="margin-bottom: 8px;" type="submit" class="btn theme-btn btn-lg">@if(isset($item)) Modificar @else Agregar y seguir comprando @endif</button><br/>
                        <a href="{{url()->previous()}}" class="btn btn-link"><i class="fa fa-arrow-left"></i> Regresar</a>
                    </div>
                </div>
                <div class="col-xs-12 col-md-12 col-lg-4">
                    <div class="sidebar-wrap">
                        <div class="widget widget-cart">
                            <div class="widget-heading">
                                <h3 class="widget-title text-dark">
                                    Personalizar
                                </h3>
                                <div class="clearfix"></div>
                            </div>
                            <div class="order-row bg-white">
                                <div class="widget-body">
                                    <div class="title-row">Cantidad</div>
                                    <div class="form-group row no-gutter">
                                        <input name="quantity" class="form-control" type="number" id="quantity" min="1"
                                               @if(isset($item) && $item->quantity) value="{{$item->quantity}}" @else value="1" @endif
                                               required>
                                    </div>
                                </div>
                            </div>
                            <div class="order-row bg-white">
                                <div class="widget-body">
                                    <div class="title-row">Indicaciones Extra</div>
                                    <div class="form-group row no-gutter">
                                        <textarea name="comentarios_cliente" maxlength="150" class="form-control txtConteoCaracteres" placeholder="Cualquier comentario de tu platillo que no afecte su precio. Ej: sin Picante">@if(isset($item->options['comentarios_cliente']) && $item->options['comentarios_cliente']){{$item->options['comentarios_cliente']}}@endif</textarea>
                                        <div class="conteoCaracteresContenedor"><span class="conteoCaracteres">0</span> / 150</div>
                                    </div>
                                </div>
                            </div>
                            <div class="widget-body">
                                <div class="price-wrap text-xs-center">
                                    <!--
                                    <p>TOTAL</p>
                                    <h3 class="value"><strong>$ 25,49</strong></h3>
                                    <p>Free Shipping</p>
                                    -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                    <div class="solo_movil">
                        <button id="btnGoToCheckoutMobile" style="margin-bottom: 8px;" type="button" class="btn theme-btn btn-lg">@if(isset($item)) Modificar e ir a Pagar @else Agregar e ir a pagar @endif</button><br/>
                        <button style="margin-bottom: 8px;" type="submit" class="btn theme-btn btn-lg">@if(isset($item)) Modificar @else Agregar y seguir comprando @endif</button><br/>
                        <a href="{{url()->previous()}}" class="btn btn-link"><i class="fa fa-arrow-left"></i> Regresar</a>
                </div>
            </div>
            </form>
        </div>
    </section>
    <script type="application/javascript">
        $(document).ready(function(){
          $('#btnGoToCheckout').click(function(){
              $('#hdnGoToCheckout').val(true)
              $('#frmItem').submit();
          });
            $('#btnGoToCheckoutMobile').click(function(){
                $('#hdnGoToCheckout').val(true)
                $('#frmItem').submit();
            });
        });
    </script>

@endsection